### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by shingohu** [greenrobot/ObjectBox#121]
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5113)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.UnsatisfiedLinkError: Couldn't load objectbox from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.naodong.shenluntiku-1.apk", zip file "/data/data/com.naodong.shenluntiku/code_cache/secondary-dexes/com.naodong.shenluntiku-1.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/com.naodong.shenluntiku-1, /vendor/lib, /system/lib]]]: findLibrary returned null
	at java.lang.Runtime.loadLibrary(Runtime.java:358)
	at java.lang.System.loadLibrary(System.java:526)
	at io.objectbox.internal.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:33)
	at io.objectbox.BoxStore.<init>(BoxStore.java:138)
	at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:147)
	at com.naodong.shenluntiku.mvp.model.data.manager.BoxManager.<init>(BoxManager.java:36)
	at com.naodong.shenluntiku.mvp.model.data.manager.BoxManager.getInstance(BoxManager.java:27)

Version  0.9.12

**Comment by shingohu** [comment]
I am sorry
